config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions

  root to: 'files#index'
  resources :files
  post 'upload', to: 'files#upload'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email
  validates :password, :length => { :minimum => 5 }
  validates_confirmation_of :password
  after_create :create_user_directory

  has_many :user_files

  def get_user_dir
    "#{Rails.root}/storage/#{self.id}"
  end

  private

  def create_user_directory
    Dir.mkdir(get_user_dir)
  end
end

app/models/user_file.rb
class UserFile < ActiveRecord::Base
  belongs_to :user

  before_destroy :remove_file_from_disk

  private

  def remove_file_from_disk
    puts "ok removing file called"
    File.delete(self.location)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_filter :authorize, only: [:upload, :delete]

  def index
    @user = current_user
    @files = @user.user_files if !@user.nil?
  end

  def upload
    uploaded_io = params[:upload]
    user = current_user
    user_dir = user.get_user_dir
    file_path = write_file_to_disk(user_dir, uploaded_io)
    user.user_files.create(:name => "#{file_path.split('/').last}", :location => "#{file_path}")
    redirect_to root_url
  end

  def destroy
    @my_file = UserFile.find(params[:id])
    # Only the user who created the file can destroy it.
    if @my_file.user_id == current_user.id
      @my_file.destroy
      redirect_to root_url
    else
      flash.now.alert = "Error! You are not authorized to delete this file!"
      redirect_to root_url, flash: {error: "Not authorized!"}
    end
  end

  private

  def write_file_to_disk(dir, file_io)
    full_file_path = "#{dir}/#{file_io.original_filename}"
    File.open(full_file_path, 'wb') do |file|
      file.write(file_io.read)
    end
    full_file_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/files/index.html.erb
<% if !@user.nil? %>
    <h1>Files</h1>
    <% if @files.count > 0 %>
    <table>
      <% @files.each do |each_file| %>
          <tr>
            <td><%= each_file.name %></td>
            <td><%= link_to 'Delete', file_path(each_file), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    </table>
    <% else %>
     <p>No files uploaded!</p>
    <% end %>
    <p>
    <%= form_tag({action: :upload}, multipart: true) do %>
        <%= file_field_tag 'upload' %>
        <p class="button"><%= submit_tag "Submit" %>
    <% end %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileUploadWithoutGems</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="user_header">
    <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path %>
    <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>